### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by szaimen** [GAS85/nextcloud_scripts#6]
Hey, 

I am planning to use the nextcloud-av-notification.sh in another open source project.
What is the license of this script?

Thanks!

**Comment by szaimen** [comment]
BTW: is your recomendation to run this script every half an hour via a cronjob? There is no documentation I am aware of concerning this...

**Comment by GAS85** [comment]
I add  AGPL-3.0 License as it done for a NC server part, so that could be used together is needed.
As I understood this will not prevent you from using it in a open source project.

>  BTW: is your recomendation to run this script every half an hour via a cronjob? There is no documentation I am aware of concerning this...

It is up to you, just adjust https://github.com/GAS85/nextcloud_scripts/blob/master/nextcloud-av-notification.sh#L12 to your cron period.

Basically on a stable system you are producing very less logs, so you can easily go to 1 hour and more. Even it will do a try for a search in a rotated log file (I did't test nextcloud internall rotation, only with my System log rotation).

**Comment by szaimen** [comment]
Hey, thanks for choosing a license. I guess GPL would better fit for this Repo than AGPL but of course this is up to you.
GPL projects can also get used in AGPL projects but not the other way araound, afaik.
So if it is licensed under AGPL it could get used together with Nextcloud but not used in GPL projects like e.g. the Nextcloud-VM

> It is up to you, just adjust https://github.com/GAS85/nextcloud_scripts/blob/master/nextcloud-av-notification.sh#L12 to your cron period.
> 
> Basically on a stable system you are producing very less logs, so you can easily go to 1 hour and more. Even it will do a try for a search in a rotated log file (I did't test nextcloud internall rotation, only with my System log rotation).

Thanks for that, I will have a look.

**Comment by GAS85** [comment]
Good hint, I will do update.

**Comment by szaimen** [comment]
Thanks!
